### ISSUE TITLE
Enigma crash due to AttributeError: 'MessageBox' object has no attribute 'timerRunning' 

### ISSUE THREAD

**Issue by hroemer** [m4dhouse/MadMax-Atv#2]
Running OpenATV 7.0/7.1 with (Enigma 2.8) I frequently experience crashes while:

* playing media content (playlist) and skipping / pausing
* as soon as recordings start in the background

This ultimately results in an infinite loop until the timer - hence the planned recording time - ends.
Here's part of the crash log:

```
./enigma2_crash_1649535000.log:20:32:38.9579 AttributeError: 'MessageBox' object has no attribute 'timerRunning'
./enigma2_crash_1649535000.log-20:32:38.9580 [ePyObject] (PyObject_CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation object at 0xae7cc940>>,(0,)) failed)
./enigma2_crash_1649535000.log-22:10:00.1627 Traceback (most recent call last):
./enigma2_crash_1649535000.log-22:10:00.1628   File "/usr/lib/enigma2/python/Navigation.py", line 273, in dispatchRecordEvent
./enigma2_crash_1649535000.log-22:10:00.1633   File "/usr/lib/enigma2/python/RecordTimer.py", line 1135, in gotRecordEvent
./enigma2_crash_1649535000.log-22:10:00.1660   File "/usr/lib/enigma2/python/Tools/Notifications.py", line 74, in AddPopup
./enigma2_crash_1649535000.log-22:10:00.1664   File "/usr/lib/enigma2/python/Tools/Notifications.py", line 33, in AddNotificationWithID
./enigma2_crash_1649535000.log-22:10:00.1666   File "/usr/lib/enigma2/python/Tools/Notifications.py", line 16, in __AddNotification
./enigma2_crash_1649535000.log-22:10:00.1669   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 4514, in checkNotificationsIfExecing
./enigma2_crash_1649535000.log-22:10:00.1672   File "/usr/lib/enigma2/python/Screens/InfoBarGenerics.py", line 4540, in checkNotifications
./enigma2_crash_1649535000.log-22:10:00.1675   File "/usr/lib/enigma2/python/StartEnigma.py", line 164, in open
./enigma2_crash_1649535000.log-22:10:00.1689     dialog = self.current_dialog = self.instantiateDialog(screen, *arguments, **kwargs)
./enigma2_crash_1649535000.log-22:10:00.1690   File "/usr/lib/enigma2/python/StartEnigma.py", line 103, in instantiateDialog
./enigma2_crash_1649535000.log-22:10:00.1696     return self.doInstantiateDialog(screen, arguments, kwargs, self.desktop)
./enigma2_crash_1649535000.log-22:10:00.1696   File "/usr/lib/enigma2/python/StartEnigma.py", line 130, in doInstantiateDialog
./enigma2_crash_1649535000.log-22:10:00.1700     dialog.applySkin()
./enigma2_crash_1649535000.log-22:10:00.1701   File "/usr/lib/enigma2/python/Screens/Screen.py", line 244, in applySkin
./enigma2_crash_1649535000.log-22:10:00.1706   File "/usr/lib/enigma2/python/Screens/Screen.py", line 274, in createGUIScreen
./enigma2_crash_1649535000.log-22:10:00.1709   File "skin applet", line 2, in <module>
```

Any ideas how to fix this?

**Comment by hroemer** [comment]
this small change in `skin.xml` will do it:

```python
      <applet type="onLayoutFinish">
from enigma import eSize, ePoint
titleheight = 0
if hasattr(self, 'timerRunning') and self.timerRunning:
  titleheight = 10
else:
  titleheight = 0
  self.setTitle("")
```

**Comment by m4dhouse** [comment]
Fixed, thank you so much
